name: Deploy HTML Changes to GitHub Pages

on:
  push:
    paths:
      - '**/*.html'
      - '**/*.css'
      - '**/*.js'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.svg'
      - '**/*.ico'
      - '**/*.txt'
      - '**/*.pdf'
      - 'robots.txt'
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deploy all files'
        required: false
        default: false
        type: boolean

env:
  FORCE_COLOR: 1

jobs:
  deploy-html:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Install Python dependencies for GenList.py
      run: |
        python -m pip install --upgrade pip
        pip install first
    
    - name: Generate ukulele-song-archive.html
      run: |
        echo "Running GenList.py from root directory to generate ukulele-song-archive.html..."
        python music/scripts/GenList.py music ukulele-song-archive.html --intro --no-genPDF
        echo "Generated ukulele-song-archive.html"
        ls -la ukulele-song-archive.html || echo "Archive file not found"
    
    - name: Prepare files for deployment (including ignored files)
      run: |
        # Create a temporary directory for deployment
        mkdir -p deploy_temp
        # Copy all files (including ignored ones) except git and deploy directories
        find . -maxdepth 1 -not -name '.' -not -name 'deploy_temp' -not -name '.git' -not -name '.github' -exec cp -r {} deploy_temp/ \;
        # List what we're deploying
        echo "Files being deployed:"
        ls -la deploy_temp/ukulele-song-archive.html || echo "Archive file missing"
        echo "Key files:"
        ls -la deploy_temp/*.html | head -5 || echo "No HTML files found"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy_temp
        destination_dir: .
        keep_files: true
        commit_message: '🌐 Update website files and song archive'
